### ISSUE TITLE
importing style and path img

### ISSUE THREAD

**Issue by serjo96** [alicoding/react-webpack-babel#279]
Did not understand about importing styles. I'm iporing in the APP component index.scss in which I import the rest of the styles, but when then i start build, there is a conflict with the paths of the images in CSS.
Img folder is in src folder
I may use only css module styles and i need import any css to my component?

**Comment by alicoding** [comment]
Is there example, error or anything you can show us?

**Comment by serjo96** [comment]
sure
`WebpackCleanupPlugin: 5 file(s) deleted.
Hash: 6103840634b615b36745
Version: webpack 2.4.1
Time: 6206ms
                  Asset       Size  Chunks                    Chunk Names
152f55a01a5fb5acdfc3.js     323 kB       0  [emitted]  [big]  main
             index.html  405 bytes          [emitted]         
   [1] ./~/react/react.js 56 bytes {0} [built]
       [] -> factory:259ms building:13ms = 272ms
  [17] ./~/babel-runtime/helpers/possibleConstructorReturn.js 542 bytes {0} [built]
       [] -> factory:63ms building:265ms = 328ms
  [22] ./~/react-router-dom/es/index.js 925 bytes {0} [built]
       [] -> factory:266ms building:29ms = 295ms
  [58] ./~/react-redux/es/index.js 230 bytes {0} [built]
       [] -> factory:266ms building:28ms = 294ms
 [107] ./styles/index.scss 3.26 kB {0} [built] [failed] [1 error]
       [] -> factory:228ms building:2601ms = 2829ms
 [113] ./src/App.jsx 3.26 kB {0} [built]
       [] -> factory:6ms building:229ms dependencies:31ms = 266ms
 [173] (webpack)/buildin/module.js 517 bytes {0} [built]
       [] -> factory:259ms building:14ms = 273ms
 [174] ./src/index.jsx 1.86 kB {0} [built]
       [] -> factory:33ms building:614ms = 647ms
 [198] ./src/containers/head/Head.jsx 2.47 kB {0} [built]
       [] -> factory:35ms building:92ms dependencies:191ms = 318ms
 [199] ./src/containers/main/Main.jsx 3.77 kB {0} [built]
       [] -> factory:35ms building:214ms dependencies:71ms = 320ms
 [201] ./src/reducers/reducers.js 3.49 kB {0} [built]
       [] -> factory:12ms building:67ms = 79ms
 [202] ./src/store/configureStore.js 1.05 kB {0} [built]
       [] -> factory:8ms building:249ms = 257ms
 [279] ./~/react-dom/index.js 59 bytes {0} [built]
       [] -> factory:264ms building:25ms = 289ms
 [345] ./~/react-hot-loader/index.js 41 bytes {0} [built]
       [] -> factory:265ms building:25ms = 290ms
 [411] multi ./src/index.jsx ./styles/index.scss 40 bytes {0} [built]
        factory:0ms building:1ms = 1ms
    + 397 hidden modules

ERROR in ./styles/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'
    at factoryCallback (D:\work\move-search\node_modules\webpack\lib\Compilation.js:260:39)
    at factory (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at D:\work\move-search\node_modules\async\dist\async.js:3838:9
    at D:\work\move-search\node_modules\async\dist\async.js:421:16
    at iteratorCallback (D:\work\move-search\node_modules\async\dist\async.js:996:13)
    at D:\work\move-search\node_modules\async\dist\async.js:906:16
    at D:\work\move-search\node_modules\async\dist\async.js:3835:13
    at resolvers.normal.resolve (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:130:23)
    at onResolved (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (D:\work\move-search\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at D:\work\move-search\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (D:\work\move-search\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:123:11)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
 @ multi ./src/index.jsx ./styles/index.scss

ERROR in ./styles/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'
    at factoryCallback (D:\work\move-search\node_modules\webpack\lib\Compilation.js:260:39)
    at factory (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at D:\work\move-search\node_modules\async\dist\async.js:3838:9
    at D:\work\move-search\node_modules\async\dist\async.js:421:16
    at iteratorCallback (D:\work\move-search\node_modules\async\dist\async.js:996:13)
    at D:\work\move-search\node_modules\async\dist\async.js:906:16
    at D:\work\move-search\node_modules\async\dist\async.js:3835:13
    at resolvers.normal.resolve (D:\work\move-search\node_modules\webpack\lib\NormalModuleFactory.js:130:23)
    at onResolved (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (D:\work\move-search\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at D:\work\move-search\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (D:\work\move-search\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at innerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\Resolver.js:123:11)
    at loggingCallbackWrapper (D:\work\move-search\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at D:\work\move-search\node_modules\tapable\lib\Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (D:\work\move-search\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)

ERROR in D:\work\move-search\node_modules\extract-text-webpack-plugin\loader.js??ref--9-0!D:\work\move-search\node_modules\style-loader\index.js!D:\work\move-search\node_modules\css-loader\index.js?sourceMap&localIdentName=[local]___[hash:base64:5]!D:\work\move-search\node_modules\sass-loader\lib\loader.js?outputStyle=expanded!D:\work\move-search\styles\index.scss doesn't export content
Child html-webpack-plugin for "index.html":
       [0] ./~/html-webpack-plugin/~/lodash/lodash.js 540 kB {0} [built]
           [] -> factory:465ms building:345ms = 810ms
       [1] ./~/html-webpack-plugin/lib/loader.js!./src/template.html 756 bytes {0} [built]
            factory:16ms building:16ms = 32ms
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
           [] -> factory:68ms building:14ms = 82ms
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
           [] -> factory:68ms building:14ms = 82ms
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
           [] -> factory:27ms building:50ms = 77ms
       [1] ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./styles/clear.css 3.92 kB {0} [built]
           [] -> factory:25ms building:50ms dependencies:0ms = 75ms
       [2] ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 22.4 kB {0} [built]
            factory:1ms building:2504ms = 2505ms
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:8660-8689
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-green.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3056-3104
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-blue.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3200-3247
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
           [] -> factory:1ms building:0ms = 1ms
       [1] ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./styles/clear.css 3.92 kB {0} [built]
           [] -> factory:1ms building:5ms dependencies:0ms = 6ms
       [2] ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 22.4 kB {0} [built]
            factory:0ms building:68ms = 68ms
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:8660-8689
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-green.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3056-3104
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-blue.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3200-3247
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-webpack-babel@0.0.3 build: `webpack --config webpack.production.config.js --progress --profile --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-webpack-babel@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-10-23T11_53_08_080Z-debug.log

Process finished with exit code 2
`

**Comment by serjo96** [comment]
Sure

ERROR in ./styles/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'

ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../img/spinner.gif' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:8660-8689
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-green.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3056-3104
    
    ERROR in ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss
    Module not found: Error: Can't resolve '../../img/powered-by-square-blue.svg' in 'D:\work\move-search\styles'
     @ ./~/css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?outputStyle=expanded!./styles/index.scss 8:3200-3247

**Comment by serjo96** [comment]
Now i add my styles to my components and this problem stil have
I think i found problem, Its urlpath,

**Comment by alicoding** [comment]
Glad you figured it out!
