### ISSUE TITLE
Can't run `npm run build/dev`: Unexpected token (8:3) index.jsx

### ISSUE THREAD

**Issue by cmpis** [alicoding/react-webpack-babel#77]
When I try to run build or dev I get this error (only listed build output)

```
$ npm run build

> react-webpack-babel@0.0.2 build /Users/cp/Code/proj/frontend/static/react
> NODE_ENV=production webpack -p --config webpack.production.config.js --progress --profile --colors

432ms build modules
1ms seal
2ms optimize
1ms hashing
3ms create chunk assets
1ms additional chunk assets
42ms optimize chunk assets
1ms optimize assets
2ms emit
Hash: a15466a376457c6f3383
Version: webpack 1.13.0
Time: 502ms
    Asset       Size  Chunks             Chunk Names
bundle.js  286 bytes       0  [emitted]  main
   [0] multi main 28 bytes {0} [built] [1 error]
       factory:0ms building:1ms = 1ms
    + 1 hidden modules

ERROR in ./index.jsx
Module build failed: SyntaxError: /Users/cp/Code/proj/frontend/static/react/index.jsx: Unexpected token (8:3)
   6 | 	render() {
   7 | 		return (
>  8 | 			<div>Simple React + Babel + Bootstrap + Webpack</div>
     | 			^
   9 | 		);
  10 | 	}
  11 | }
    at Parser.pp.raise (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:517:12)
    at Parser.pp.parseExprSubscripts (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:590:26)
    at Parser.pp.parseExprAtom (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:476:19)
    at Parser.pp.parseExprSubscripts (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExpression (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:92:19)
    at Parser.pp.parseReturnStatement (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:333:26)
    at Parser.pp.parseStatement (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:107:19)
    at Parser.pp.parseBlockBody (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseBlock (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:510:8)
    at Parser.pp.parseFunctionBody (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:913:22)
    at Parser.pp.parseMethod (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/expression.js:882:8)
    at Parser.pp.parseClassMethod (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:823:8)
    at Parser.pp.parseClassBody (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:784:10)
    at Parser.pp.parseClass (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:666:8)
    at Parser.pp.parseStatement (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:102:19)
    at Parser.pp.parseExportDeclaration (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:906:15)
    at Parser.pp.parseExport (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:894:29)
    at Parser.pp.parseStatement (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:141:81)
    at Parser.pp.parseBlockBody (/Users/cp/Code/proj/frontend/static/react/node_modules/babylon/lib/parser/statement.js:529:21)
 @ multi main
```

Unsure what is wrong. Used Node 0.12.12 and 6.x. Both had the same error. The index looks fine except it's not being converted before node gets to it.

**Comment by alicoding** [comment]
Still having this issue? Sorry for the late reply

**Comment by zouxuoz** [comment]
@cmpis Looks like you are missing .babelrc with es2015 and react presets.

**Comment by surajadh** [comment]
I got the exact same error for missing .babelrc and got resolved as soon as I added one. I am getting following warning though:
WARNING in bundle.js from UglifyJs
Condition always true [./~/react/lib/ReactDOMComponentTree.js:95,0]
Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
Condition always true [./~/react/lib/ReactNodeTypes.js:33,0]
Condition always true [./~/react/lib/instantiateReactComponent.js:82,0]
Condition always true [./~/react/lib/ReactDOMComponent.js:879,0]
Condition always true [./~/react/lib/ReactMultiChild.js:223,0]
Condition always true [./~/react/lib/ReactMultiChild.js:243,0]
Condition always true [./~/react/lib/findDOMNode.js:50,0]
Condition always true [./~/react/lib/findDOMNode.js:52,0]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always false [./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.min.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.min.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.min.css:7,0]

but build files are getting generated.

**Comment by alicoding** [comment]
Closing this issue since `.babelrc` file was added and the warning is just to inform the user what UglifyJs has changed after spitting out the code.
