### ISSUE TITLE
ERROR in ./index.jsx

### ISSUE THREAD

**Issue by brw31415** [alicoding/react-webpack-babel#9]
ERROR in ./index.jsx
Module build failed: ReferenceError: [BABEL] /home/brw314/react/react-webpack-babel/index.jsx: Unknown op
tion: /home/brw314/react/react-webpack-babel/.babelrc.presets                                            
    at Logger.error (/home/brw314/node_modules/babel-core/lib/transformation/file/logger.js:58:11)       
    at OptionManager.mergeOptions (/home/brw314/node_modules/babel-core/lib/transformation/file/options/o
ption-manager.js:126:29)                                                                                 
    at OptionManager.addConfig (/home/brw314/node_modules/babel-core/lib/transformation/file/options/opti
on-manager.js:107:10)                                                                                    
    at OptionManager.findConfigs (/home/brw314/node_modules/babel-core/lib/transformation/file/options/op
tion-manager.js:168:35)                                                                                  
    at OptionManager.init (/home/brw314/node_modules/babel-core/lib/transformation/file/options/option-ma
nager.js:229:12)                                                                                         
    at File.initOptions (/home/brw314/node_modules/babel-core/lib/transformation/file/index.js:147:75)   
    at new File (/home/brw314/node_modules/babel-core/lib/transformation/file/index.js:137:22)           
    at Pipeline.transform (/home/brw314/node_modules/babel-core/lib/transformation/pipeline.js:164:16)   
    at transpile (/home/brw314/node_modules/babel-loader/index.js:12:22)                                 
    at Object.module.exports (/home/brw314/node_modules/babel-loader/index.js:71:12)                     
 @ multi main

**Comment by alicoding** [comment]
@brw31415 have you run `npm install` after the update?

**Comment by brw31415** [comment]
ok, yea, that works, thanks!

**Comment by alicoding** [comment]
glad that works for you :)
